MAX_EXPORTED_MESSAGES: 1000000
ALL_COLUMNS:
  - timestamp
  - conversationId
  - conversationWithName
  - senderName
  - outgoing
  - text
  - language
  - platform

hangouts:
  DEFAULT_RAW_LOCATION: 'raw_data/hangouts/Hangouts.json'
  OUTPUT_PICKLE_NAME: 'hangouts.pkl'
messenger:
  DEFAULT_RAW_LOCATION: 'raw_data/messenger'
  OUTPUT_PICKLE_NAME: 'messenger.pkl'
telegram_api:
  USER_DIALOG_MESSAGES_LIMIT: 100000
  OUTPUT_PICKLE_NAME: 'telegram_api.pkl'
telegram_json:
  DEFAULT_RAW_LOCATION: 'raw_data/telegram/result.json'
  OUTPUT_PICKLE_NAME: 'telegram_json.pkl'
whatsapp:
  DEFAULT_RAW_LOCATION: 'raw_data/whatsapp'
  OUTPUT_PICKLE_NAME: 'whatsapp.pkl'
